name: RedPanda-CPP Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019] # macos
        version: ['5.12.11','5.12.10']  #latest 5.15.2 '5.9.9''6.2'
    steps:
      
      - uses: actions/checkout@v2
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt with options
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.version }}
          tools: 'tools_ifw,4.1.1,qt.tools.ifw.41 tools_qtcreator,5.0.2-0,qt.tools.qtcreator'

      - name: Configure test project on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_DIR%/lib/cmake
          qmake
        shell: cmd
          
      - name: Configure test project on unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          ls $Qt5_DIR/lib/cmake
          qmake
        shell: bash
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: test
          # A file, directory or wildcard pattern that describes what to upload
          path: ./
          # The desired behavior if no files are found using the provided path.
